//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaInformacionAdicional
    {
        public long IDActaInformacionAdicional { get; set; }
        public long ActaID { get; set; }
        public string AcuerdoConformidad { get; set; }
        public string Firmas { get; set; }
    }
}
