//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acta
    {
        public long IDActa { get; set; }
        public string CodigoActa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int ElaboradoPor { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> NumeroReunion { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public string ReferenciaCliente { get; set; }
        public string AlcanceObjetivo { get; set; }
        public string FacilitadorModerador { get; set; }
        public Nullable<int> CodigoCotizacionID { get; set; }
        public string CodigoCotizacion { get; set; }
        public string Cliente { get; set; }
        public string NombreProyecto { get; set; }
        public string DescripcionProyecto { get; set; }
        public string Observaciones { get; set; }
        public bool Suspendida { get; set; }
        public int TipoActaID { get; set; }
        public bool Estado { get; set; }
    }
}
