//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AprobacionCotizacion
    {
        public int IDCotizacionAprobada { get; set; }
        public int CotizacionID { get; set; }
        public int CodigoCotizacionID { get; set; }
        public string Observacion { get; set; }
        public int estatus_codigo { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
    }
}
