//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class CalculoValoresFacturaPTOP
    {
        public Nullable<decimal> valor_documento { get; set; }
        public Nullable<decimal> valor_descuento { get; set; }
        public Nullable<decimal> subtotal_documento { get; set; }
        public Nullable<decimal> valor_iva { get; set; }
        public Nullable<decimal> total_documento { get; set; }
        public Nullable<bool> Correcto { get; set; }
        public string Error { get; set; }
    }
}
