//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class CamposPersonalizadosSolicitud
    {
        public int id_campo_personalizado { get; set; }
        public Nullable<int> id_solicitud { get; set; }
        public string nombre_campo { get; set; }
    }
}
