//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_cliente { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> referido { get; set; }
        public Nullable<int> intermediario { get; set; }
        public Nullable<int> tipo_zoho { get; set; }
        public Nullable<int> tipo_cliente { get; set; }
        public Nullable<int> tamanio_empresa { get; set; }
        public Nullable<int> etapa_cliente { get; set; }
        public Nullable<int> potencial_crecimiento { get; set; }
        public Nullable<int> categorizacion_cliente { get; set; }
        public string ruc_ci_cliente { get; set; }
        public string razon_social_cliente { get; set; }
        public string nombre_comercial_cliente { get; set; }
        public Nullable<decimal> ingresos_anuales_cliente { get; set; }
        public Nullable<int> sector { get; set; }
        public Nullable<int> pais { get; set; }
        public Nullable<int> ciudad { get; set; }
        public string direccion_cliente { get; set; }
        public Nullable<bool> estado_cliente { get; set; }
        public Nullable<bool> usar_organigrama { get; set; }
    }
}
