//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comercio
    {
        public int id_comercio { get; set; }
        public string id_comercio_predictive { get; set; }
        public string nombre_comercio { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_salida_produccion { get; set; }
        public Nullable<System.DateTime> fecha_inactivo { get; set; }
        public Nullable<int> id_estatus_contrato { get; set; }
        public Nullable<int> id_tipo_subsidio { get; set; }
        public Nullable<int> id_agrupacion { get; set; }
        public Nullable<bool> compartido_ptop { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> porcentaje_iva { get; set; }
        public Nullable<bool> estado_comercio { get; set; }
        public Nullable<bool> cobro_porcentaje { get; set; }
    }
}
