//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ComentariosSolicitudInfo
    {
        public long IDComentarioSolicitud { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public byte[] ArchivoAdjunto { get; set; }
        public int SolicitudID { get; set; }
        public Nullable<System.DateTime> fecha_hora_solicitud { get; set; }
        public string NombresCompletosSolicitante { get; set; }
        public string codigo_cotizacion { get; set; }
        public bool EstadoComentarioSolicitud { get; set; }
        public string Respuestas { get; set; }
        public string IDSRespuestas { get; set; }
    }
}
