//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidacionPrefactura
    {
        public int IDConsolidacionPrefactura { get; set; }
        public int id_facturacion_safi { get; set; }
        public int id_facturacion_safi_consolidada { get; set; }
        public System.DateTime FechaConsolidacion { get; set; }
        public int UsuarioID { get; set; }
    }
}
