//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosCodigoCotizacion
    {
        public int idContactoCodigoCotizacion { get; set; }
        public Nullable<int> idContacto { get; set; }
        public Nullable<int> idCodigoCotizacion { get; set; }
    }
}
