//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class CostosSublineaNegocioInfo
    {
        public int IDCostoSublineaNegocio { get; set; }
        public int CodigoCatalogoSublineaNegocio { get; set; }
        public int CodigoCatalogoTipoSolicitud { get; set; }
        public string TextoCatalogoSublineaNegocio { get; set; }
        public string TextoCatalogoTipoSolicitud { get; set; }
        public decimal Valor { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> CodigoCatalogoSubTipoSolicitud { get; set; }
        public string TextoCatalogoSubTipoSolicitud { get; set; }
    }
}
