//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoSublineaNegocio
    {
        public int IDCostoSublineaNegocio { get; set; }
        public int CatalogoSublineaNegocioID { get; set; }
        public int CatalogoTipoSolicitudID { get; set; }
        public decimal Valor { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> CatalogoSubTipoSolicitudID { get; set; }
    }
}
