//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class DatosSolicitudCliente
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Tipo { get; set; }
        public string Subtipo { get; set; }
        public string Marca { get; set; }
        public string Solicitante { get; set; }
        public string Cargo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Empresa { get; set; }
        public string Mail { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Area1 { get; set; }
        public string Area2 { get; set; }
        public string Implementacion { get; set; }
        public string OP { get; set; }
        public string MKT { get; set; }
        public string Estado { get; set; }
        public string CodigoSolicitud { get; set; }
        public System.DateTime fecha_hora_fin_solicitud { get; set; }
        public string AreaEncargada { get; set; }
        public string Asunto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Urgente { get; set; }
        public string TextoCatalogoEstadoSolicitud { get; set; }
        public Nullable<int> id_estado_solicitud { get; set; }
        public string CodigoCatalogoEstadoSolicitud { get; set; }
    }
}
