//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizador
    {
        public int id_detalle_cotizador { get; set; }
        public Nullable<int> id_cotizador { get; set; }
        public string entregable { get; set; }
        public Nullable<decimal> costo_total_entregable { get; set; }
        public Nullable<int> tipo_servicio { get; set; }
        public Nullable<int> cantidad_servicio { get; set; }
        public Nullable<decimal> valor_unitario_servicio { get; set; }
        public Nullable<decimal> costo_total_servicio { get; set; }
        public Nullable<int> tipo_gestion { get; set; }
        public Nullable<int> cantidad_gestion { get; set; }
        public Nullable<decimal> valor_unitario_gestion { get; set; }
        public Nullable<decimal> costo_total_gestion { get; set; }
    }
}
