//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesActa
    {
        public long IDDetalleActa { get; set; }
        public long ActaID { get; set; }
        public Nullable<int> DetalleActaParticipantesID { get; set; }
        public Nullable<int> DetalleActaResponsablesClienteID { get; set; }
        public Nullable<int> DetalleActaEntregablesID { get; set; }
        public Nullable<int> DetalleActaTemasTratarID { get; set; }
        public Nullable<int> DetalleActaAcuerdosID { get; set; }
        public Nullable<int> DetalleActaCondicionesGeneralesID { get; set; }
        public Nullable<int> DetalleActaClienteID { get; set; }
        public Nullable<int> DetalleActaContabilidadID { get; set; }
    }
}
