//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class DetalleUltimoAvance
    {
        public int id_detalle_proyecto { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<System.DateTime> fecha_avance { get; set; }
        public Nullable<decimal> porcentaje_avance { get; set; }
        public string descripcion_avance { get; set; }
        public string ejecutado { get; set; }
        public string en_ejecucion { get; set; }
        public string bloqueantes { get; set; }
        public string proximos_pasos { get; set; }
    }
}
