//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int id_empresa { get; set; }
        public string cedula_ruc_pasaporte { get; set; }
        public string razon_social { get; set; }
        public string nombre_comercial { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string pagina_web { get; set; }
        public string logo { get; set; }
        public string representante_legal { get; set; }
        public Nullable<bool> obligado_llevar_contabilidad { get; set; }
    }
}
