//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class V1791219058001_SAFI_3Entities : DbContext
    {
        public V1791219058001_SAFI_3Entities()
            : base("name=V1791219058001_SAFI_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ActualizarPresupuestosSAFI(Nullable<int> tipoAccion, string numeroPrefactura, string numeroPrefacturaConsolidada)
        {
            var tipoAccionParameter = tipoAccion.HasValue ?
                new ObjectParameter("tipoAccion", tipoAccion) :
                new ObjectParameter("tipoAccion", typeof(int));
    
            var numeroPrefacturaParameter = numeroPrefactura != null ?
                new ObjectParameter("numeroPrefactura", numeroPrefactura) :
                new ObjectParameter("numeroPrefactura", typeof(string));
    
            var numeroPrefacturaConsolidadaParameter = numeroPrefacturaConsolidada != null ?
                new ObjectParameter("numeroPrefacturaConsolidada", numeroPrefacturaConsolidada) :
                new ObjectParameter("numeroPrefacturaConsolidada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPresupuestosSAFI", tipoAccionParameter, numeroPrefacturaParameter, numeroPrefacturaConsolidadaParameter);
        }
    }
}
