//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class EstructuraOrganigramaInfo
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> parent { get; set; }
        public string usuario { get; set; }
        public string cargo { get; set; }
        public string departamento { get; set; }
        public string codigo { get; set; }
        public string mail { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
