//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class FacturaPTOPSAFI
    {
        public int id_factura_PTOP { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string correos { get; set; }
        public string detalle { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string observaciones { get; set; }
        public string numero_factura { get; set; }
        public string numero_nota_credito { get; set; }
        public Nullable<bool> enviar_CRM { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> secuencial { get; set; }
        public string detalle_facturas { get; set; }
    }
}
