//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionContratosComercios
    {
        public int id_gestion_comercio { get; set; }
        public Nullable<int> id_comercio { get; set; }
        public Nullable<int> id_estatus_contrato_anterior { get; set; }
        public Nullable<int> id_estatus_contrato_actual { get; set; }
        public Nullable<int> id_canal_comunicacion { get; set; }
        public Nullable<System.DateTime> fecha_comunicacion { get; set; }
        public Nullable<int> id_tipificacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string observaciones { get; set; }
    }
}
