//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionPPMEntities : DbContext
    {
        public GestionPPMEntities()
            : base("name=GestionPPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilMenu> PerfilMenu { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolPerfil> RolPerfil { get; set; }
        public virtual DbSet<Tarifario> Tarifario { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<ContactosCodigoCotizacion> ContactosCodigoCotizacion { get; set; }
        public virtual DbSet<ContactosClientes> ContactosClientes { get; set; }
        public virtual DbSet<DetalleCotizador> DetalleCotizador { get; set; }
        public virtual DbSet<Cotizador> Cotizador { get; set; }
        public virtual DbSet<SublineaNegocioCodigoCotizacion> SublineaNegocioCodigoCotizacion { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<CodigoCotizacion> CodigoCotizacion { get; set; }
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<DetalleProyectosAsignados> DetalleProyectosAsignados { get; set; }
        public virtual DbSet<ProyectosAsignados> ProyectosAsignados { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<TipoNotificacion> TipoNotificacion { get; set; }
        public virtual DbSet<TablaPlanes> TablaPlanes { get; set; }
        public virtual DbSet<ClienteLineaNegocio> ClienteLineaNegocio { get; set; }
        public virtual DbSet<GestionContratosComercios> GestionContratosComercios { get; set; }
        public virtual DbSet<CargaPTOP> CargaPTOP { get; set; }
        public virtual DbSet<Comercio> Comercio { get; set; }
        public virtual DbSet<NotaCreditoPTOP> NotaCreditoPTOP { get; set; }
        public virtual DbSet<ParametrosSistema> ParametrosSistema { get; set; }
        public virtual DbSet<AsignacionSolicitudes> AsignacionSolicitudes { get; set; }
        public virtual DbSet<AsignacionSolicitudUsuario> AsignacionSolicitudUsuario { get; set; }
        public virtual DbSet<Solicitud_Adjuntos> Solicitud_Adjuntos { get; set; }
        public virtual DbSet<Solicitud_Campos_Personalizados> Solicitud_Campos_Personalizados { get; set; }
        public virtual DbSet<Solicitud_Cliente_Usuario> Solicitud_Cliente_Usuario { get; set; }
        public virtual DbSet<Solicitud_Url_Externo> Solicitud_Url_Externo { get; set; }
        public virtual DbSet<Acta> Acta { get; set; }
        public virtual DbSet<ActaInformacionAdicional> ActaInformacionAdicional { get; set; }
        public virtual DbSet<CostoSublineaNegocio> CostoSublineaNegocio { get; set; }
        public virtual DbSet<DetalleActaAcuerdos> DetalleActaAcuerdos { get; set; }
        public virtual DbSet<DetalleActaCondicionesGenerales> DetalleActaCondicionesGenerales { get; set; }
        public virtual DbSet<DetalleActaEntregables> DetalleActaEntregables { get; set; }
        public virtual DbSet<DetalleActaParticipantes> DetalleActaParticipantes { get; set; }
        public virtual DbSet<DetalleActaResponsables> DetalleActaResponsables { get; set; }
        public virtual DbSet<DetalleActaTemasTratar> DetalleActaTemasTratar { get; set; }
        public virtual DbSet<DetallesActa> DetallesActa { get; set; }
        public virtual DbSet<Organigrama> Organigrama { get; set; }
        public virtual DbSet<SecuencialTipoActa> SecuencialTipoActa { get; set; }
        public virtual DbSet<TipoOrganigrama> TipoOrganigrama { get; set; }
        public virtual DbSet<AprobacionCotizacion> AprobacionCotizacion { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<CodigoProducto> CodigoProducto { get; set; }
        public virtual DbSet<DetalleActaCliente> DetalleActaCliente { get; set; }
        public virtual DbSet<DetalleActaContabilidad> DetalleActaContabilidad { get; set; }
        public virtual DbSet<SAFIGeneral> SAFIGeneral { get; set; }
        public virtual DbSet<ActualizacionSAFI> ActualizacionSAFI { get; set; }
        public virtual DbSet<SolicitudCliente> SolicitudCliente { get; set; }
        public virtual DbSet<ANSCliente> ANSCliente { get; set; }
        public virtual DbSet<Solicitud_Portales> Solicitud_Portales { get; set; }
        public virtual DbSet<RolMenuPermiso> RolMenuPermiso { get; set; }
        public virtual DbSet<ComentarioSolicitud> ComentarioSolicitud { get; set; }
        public virtual DbSet<RespuestaComentario> RespuestaComentario { get; set; }
        public virtual DbSet<LineaNegocio> LineaNegocio { get; set; }
        public virtual DbSet<ProdutosGeneralGestor> ProdutosGeneralGestor { get; set; }
        public virtual DbSet<ProdutosGestor> ProdutosGestor { get; set; }
        public virtual DbSet<SublineaNegocio> SublineaNegocio { get; set; }
        public virtual DbSet<SAFIGeneralDetalle> SAFIGeneralDetalle { get; set; }
        public virtual DbSet<SolicitudesDeReverso> SolicitudesDeReverso { get; set; }
        public virtual DbSet<SolicitudesDeAnulacionFactura> SolicitudesDeAnulacionFactura { get; set; }
        public virtual DbSet<SolicitudesDeNotaDeCredito> SolicitudesDeNotaDeCredito { get; set; }
        public virtual DbSet<SolicitudesDeRechazoPresupuestos> SolicitudesDeRechazoPresupuestos { get; set; }
        public virtual DbSet<ConsolidacionPrefactura> ConsolidacionPrefactura { get; set; }
    
        public virtual ObjectResult<usp_b_lista_usuario> usp_b_lista_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_lista_usuario>("usp_b_lista_usuario");
        }
    
        public virtual int usp_envia_correo_usuario(Nullable<int> id_usuario, string clave)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_envia_correo_usuario", id_usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<usp_b_usuario> usp_b_usuario(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_usuario>("usp_b_usuario", usuarioParameter, claveParameter);
        }
    
        public virtual int usp_envia_correo_usuario_generico(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_envia_correo_usuario_generico", id_usuarioParameter);
        }
    
        public virtual ObjectResult<usp_b_lista_menu_Result> usp_b_lista_menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_lista_menu_Result>("usp_b_lista_menu");
        }
    
        public virtual ObjectResult<usp_b_lista_perfil_Result> usp_b_lista_perfil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_lista_perfil_Result>("usp_b_lista_perfil");
        }
    
        public virtual ObjectResult<usp_b_lista_rol> usp_b_lista_rol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_lista_rol>("usp_b_lista_rol");
        }
    
        public virtual ObjectResult<usp_b_opci_menu_usua> usp_b_opci_menu_usua(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_opci_menu_usua>("usp_b_opci_menu_usua", id_usuarioParameter);
        }
    
        public virtual ObjectResult<usp_b_lista_catalogo> usp_b_lista_catalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_lista_catalogo>("usp_b_lista_catalogo");
        }
    
        public virtual int usp_envia_correo_usuario_reset_clave(Nullable<int> id_usuario, string clave)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_envia_correo_usuario_reset_clave", id_usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<usp_b_catalogo_codigo> usp_b_catalogo_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_catalogo_codigo>("usp_b_catalogo_codigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_b_catalogo_codigo_id> usp_b_catalogo_codigo_id(string codigo, Nullable<int> id)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_catalogo_codigo_id>("usp_b_catalogo_codigo_id", codigoParameter, idParameter);
        }
    
        public virtual ObjectResult<usp_b_nume_hijo_cata> usp_b_nume_hijo_cata(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_nume_hijo_cata>("usp_b_nume_hijo_cata", idParameter);
        }
    
        public virtual ObjectResult<usp_b_catalogo_hijos> usp_b_catalogo_hijos(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_catalogo_hijos>("usp_b_catalogo_hijos", idParameter);
        }
    
        public virtual ObjectResult<usp_b_catalogo_id> usp_b_catalogo_id(Nullable<int> id, string codigo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_catalogo_id>("usp_b_catalogo_id", idParameter, codigoParameter);
        }
    
        public virtual ObjectResult<ListadoCabeceraCotizador_Result> ListadoCabeceraCotizador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCabeceraCotizador_Result>("ListadoCabeceraCotizador");
        }
    
        public virtual ObjectResult<CodigoCotizacionInfo> ListadoCodigoCotizacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodigoCotizacionInfo>("ListadoCodigoCotizacion");
        }
    
        public virtual ObjectResult<ListadoDetalleCotizador_Result> ListadoDetalleCotizador(Nullable<int> id_cotizador)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoDetalleCotizador_Result>("ListadoDetalleCotizador", id_cotizadorParameter);
        }
    
        public virtual ObjectResult<usp_b_datos_cotizador> usp_b_datos_cotizador(Nullable<int> id_cotizador)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_datos_cotizador>("usp_b_datos_cotizador", id_cotizadorParameter);
        }
    
        public virtual ObjectResult<usp_b_datos_detalle_cotizador> usp_b_datos_detalle_cotizador(Nullable<int> id_cotizador)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_datos_detalle_cotizador>("usp_b_datos_detalle_cotizador", id_cotizadorParameter);
        }
    
        public virtual ObjectResult<usp_g_codigo_usuario> usp_g_codigo_usuario(Nullable<int> tipo_usuario)
        {
            var tipo_usuarioParameter = tipo_usuario.HasValue ?
                new ObjectParameter("tipo_usuario", tipo_usuario) :
                new ObjectParameter("tipo_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_g_codigo_usuario>("usp_g_codigo_usuario", tipo_usuarioParameter);
        }
    
        public virtual ObjectResult<CabeceraDetalleCotizador_Result> CabeceraDetalleCotizador(Nullable<int> id_cotizador)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CabeceraDetalleCotizador_Result>("CabeceraDetalleCotizador", id_cotizadorParameter);
        }
    
        public virtual ObjectResult<CodigoCotizacionGeneradoInfo> GenerarCodigoCotizacion(Nullable<int> iCodigoUsuario)
        {
            var iCodigoUsuarioParameter = iCodigoUsuario.HasValue ?
                new ObjectParameter("iCodigoUsuario", iCodigoUsuario) :
                new ObjectParameter("iCodigoUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodigoCotizacionGeneradoInfo>("GenerarCodigoCotizacion", iCodigoUsuarioParameter);
        }
    
        public virtual ObjectResult<ClientesInfo> ListadoClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientesInfo>("ListadoClientes");
        }
    
        public virtual ObjectResult<ContactosInfo> ListadoContactos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ContactosInfo>("ListadoContactos");
        }
    
        public virtual ObjectResult<ContactosClientesInfo> ListadoContactosClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ContactosClientesInfo>("ListadoContactosClientes");
        }
    
        public virtual ObjectResult<SublineaNegocioCodigoCotizacionInfo> ListadoSublineaNegocioCodigoCotizacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SublineaNegocioCodigoCotizacionInfo>("ListadoSublineaNegocioCodigoCotizacion");
        }
    
        public virtual ObjectResult<TarifarioInfo> ListadoTarifario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TarifarioInfo>("ListadoTarifario");
        }
    
        public virtual int usp_g_cierre_version_cotizador(Nullable<int> id_cotizador)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_g_cierre_version_cotizador", id_cotizadorParameter);
        }
    
        public virtual int usp_g_detalle_cotizador(Nullable<int> id_cotizador, string entregable, Nullable<decimal> costo_total_entregable, Nullable<int> tipo_servicio, Nullable<int> cantidad_servicio, Nullable<decimal> valor_unitario_servicio, Nullable<decimal> costo_total_servicio, Nullable<int> tipo_gestion, Nullable<int> cantidad_gestion, Nullable<decimal> valor_unitario_gestion, Nullable<decimal> costo_total_gestion)
        {
            var id_cotizadorParameter = id_cotizador.HasValue ?
                new ObjectParameter("id_cotizador", id_cotizador) :
                new ObjectParameter("id_cotizador", typeof(int));
    
            var entregableParameter = entregable != null ?
                new ObjectParameter("entregable", entregable) :
                new ObjectParameter("entregable", typeof(string));
    
            var costo_total_entregableParameter = costo_total_entregable.HasValue ?
                new ObjectParameter("costo_total_entregable", costo_total_entregable) :
                new ObjectParameter("costo_total_entregable", typeof(decimal));
    
            var tipo_servicioParameter = tipo_servicio.HasValue ?
                new ObjectParameter("tipo_servicio", tipo_servicio) :
                new ObjectParameter("tipo_servicio", typeof(int));
    
            var cantidad_servicioParameter = cantidad_servicio.HasValue ?
                new ObjectParameter("cantidad_servicio", cantidad_servicio) :
                new ObjectParameter("cantidad_servicio", typeof(int));
    
            var valor_unitario_servicioParameter = valor_unitario_servicio.HasValue ?
                new ObjectParameter("valor_unitario_servicio", valor_unitario_servicio) :
                new ObjectParameter("valor_unitario_servicio", typeof(decimal));
    
            var costo_total_servicioParameter = costo_total_servicio.HasValue ?
                new ObjectParameter("costo_total_servicio", costo_total_servicio) :
                new ObjectParameter("costo_total_servicio", typeof(decimal));
    
            var tipo_gestionParameter = tipo_gestion.HasValue ?
                new ObjectParameter("tipo_gestion", tipo_gestion) :
                new ObjectParameter("tipo_gestion", typeof(int));
    
            var cantidad_gestionParameter = cantidad_gestion.HasValue ?
                new ObjectParameter("cantidad_gestion", cantidad_gestion) :
                new ObjectParameter("cantidad_gestion", typeof(int));
    
            var valor_unitario_gestionParameter = valor_unitario_gestion.HasValue ?
                new ObjectParameter("valor_unitario_gestion", valor_unitario_gestion) :
                new ObjectParameter("valor_unitario_gestion", typeof(decimal));
    
            var costo_total_gestionParameter = costo_total_gestion.HasValue ?
                new ObjectParameter("costo_total_gestion", costo_total_gestion) :
                new ObjectParameter("costo_total_gestion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_g_detalle_cotizador", id_cotizadorParameter, entregableParameter, costo_total_entregableParameter, tipo_servicioParameter, cantidad_servicioParameter, valor_unitario_servicioParameter, costo_total_servicioParameter, tipo_gestionParameter, cantidad_gestionParameter, valor_unitario_gestionParameter, costo_total_gestionParameter);
        }
    
        public virtual ObjectResult<ListadoMenu> ListadoMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoMenu>("ListadoMenu");
        }
    
        public virtual int usp_envia_correo_usuario_cambio_clave(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_envia_correo_usuario_cambio_clave", id_usuarioParameter);
        }
    
        public virtual ObjectResult<GuardarCabeceraCotizador> usp_g_cabecera_cotizador(Nullable<int> id_codigo_cotizacion, Nullable<int> numero_dias, Nullable<System.DateTime> fecha_cotizacion, Nullable<System.DateTime> fechha_vencimiento, string observacion, Nullable<decimal> subtotal, Nullable<decimal> porc_descuento, Nullable<decimal> valor_descuento, Nullable<int> id_impuesto, Nullable<decimal> porcentaje_iva, Nullable<decimal> valor_iva, Nullable<decimal> total)
        {
            var id_codigo_cotizacionParameter = id_codigo_cotizacion.HasValue ?
                new ObjectParameter("id_codigo_cotizacion", id_codigo_cotizacion) :
                new ObjectParameter("id_codigo_cotizacion", typeof(int));
    
            var numero_diasParameter = numero_dias.HasValue ?
                new ObjectParameter("numero_dias", numero_dias) :
                new ObjectParameter("numero_dias", typeof(int));
    
            var fecha_cotizacionParameter = fecha_cotizacion.HasValue ?
                new ObjectParameter("fecha_cotizacion", fecha_cotizacion) :
                new ObjectParameter("fecha_cotizacion", typeof(System.DateTime));
    
            var fechha_vencimientoParameter = fechha_vencimiento.HasValue ?
                new ObjectParameter("fechha_vencimiento", fechha_vencimiento) :
                new ObjectParameter("fechha_vencimiento", typeof(System.DateTime));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("subtotal", subtotal) :
                new ObjectParameter("subtotal", typeof(decimal));
    
            var porc_descuentoParameter = porc_descuento.HasValue ?
                new ObjectParameter("porc_descuento", porc_descuento) :
                new ObjectParameter("porc_descuento", typeof(decimal));
    
            var valor_descuentoParameter = valor_descuento.HasValue ?
                new ObjectParameter("valor_descuento", valor_descuento) :
                new ObjectParameter("valor_descuento", typeof(decimal));
    
            var id_impuestoParameter = id_impuesto.HasValue ?
                new ObjectParameter("id_impuesto", id_impuesto) :
                new ObjectParameter("id_impuesto", typeof(int));
    
            var porcentaje_ivaParameter = porcentaje_iva.HasValue ?
                new ObjectParameter("porcentaje_iva", porcentaje_iva) :
                new ObjectParameter("porcentaje_iva", typeof(decimal));
    
            var valor_ivaParameter = valor_iva.HasValue ?
                new ObjectParameter("valor_iva", valor_iva) :
                new ObjectParameter("valor_iva", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GuardarCabeceraCotizador>("usp_g_cabecera_cotizador", id_codigo_cotizacionParameter, numero_diasParameter, fecha_cotizacionParameter, fechha_vencimientoParameter, observacionParameter, subtotalParameter, porc_descuentoParameter, valor_descuentoParameter, id_impuestoParameter, porcentaje_ivaParameter, valor_ivaParameter, totalParameter);
        }
    
        public virtual ObjectResult<ListadoPerfil> ListadoPerfil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPerfil>("ListadoPerfil");
        }
    
        public virtual ObjectResult<ListadoRol> ListadoRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoRol>("ListadoRol");
        }
    
        public virtual ObjectResult<ListadoTablaCostos> ListadoTablaCostos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoTablaCostos>("ListadoTablaCostos");
        }
    
        public virtual ObjectResult<ListadoUsuarios> ListadoUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoUsuarios>("ListadoUsuarios");
        }
    
        public virtual ObjectResult<ListadoCatalogo> ListadoCatalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCatalogo>("ListadoCatalogo");
        }
    
        public virtual ObjectResult<ListadoCatalogosPadres> ListadoCatalogosPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCatalogosPadres>("ListadoCatalogosPadres");
        }
    
        public virtual ObjectResult<ListadoCliente> ListadoCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCliente>("ListadoCliente");
        }
    
        public virtual ObjectResult<ListadoContacto> ListadoContacto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoContacto>("ListadoContacto");
        }
    
        public virtual ObjectResult<ListadoCabeceraCotizadorPDF> ListadoCabeceraCotizadorPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCabeceraCotizadorPDF>("ListadoCabeceraCotizadorPDF");
        }
    
        public virtual ObjectResult<usp_b_datos_usuario> usp_b_datos_usuario(string id_usuario)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_b_datos_usuario>("usp_b_datos_usuario", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ListadoOrdenMenu> ListadoOrdenMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoOrdenMenu>("ListadoOrdenMenu");
        }
    
        public virtual ObjectResult<ListadoSubcatalogos> ListadoSubcatalogos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoSubcatalogos>("ListadoSubcatalogos");
        }
    
        public virtual ObjectResult<ListadoImpuesto> ListadoImpuesto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoImpuesto>("ListadoImpuesto");
        }
    
        public virtual ObjectResult<ListadoProyectos> ListadoProyectos(Nullable<int> codigo_responsable)
        {
            var codigo_responsableParameter = codigo_responsable.HasValue ?
                new ObjectParameter("codigo_responsable", codigo_responsable) :
                new ObjectParameter("codigo_responsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoProyectos>("ListadoProyectos", codigo_responsableParameter);
        }
    
        public virtual ObjectResult<DatosProyecto> DatosProyecto(Nullable<int> id_codigo_cotizacion)
        {
            var id_codigo_cotizacionParameter = id_codigo_cotizacion.HasValue ?
                new ObjectParameter("id_codigo_cotizacion", id_codigo_cotizacion) :
                new ObjectParameter("id_codigo_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosProyecto>("DatosProyecto", id_codigo_cotizacionParameter);
        }
    
        public virtual int usp_guarda_envio_correo_cotizacion(Nullable<int> idCotizador, string cuerpo, Nullable<int> usuario, string clave)
        {
            var idCotizadorParameter = idCotizador.HasValue ?
                new ObjectParameter("idCotizador", idCotizador) :
                new ObjectParameter("idCotizador", typeof(int));
    
            var cuerpoParameter = cuerpo != null ?
                new ObjectParameter("cuerpo", cuerpo) :
                new ObjectParameter("cuerpo", typeof(string));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_guarda_envio_correo_cotizacion", idCotizadorParameter, cuerpoParameter, usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<ListadoAvanceProyectoUsuario> ListadoAvanceProyectoUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoAvanceProyectoUsuario>("ListadoAvanceProyectoUsuario", id_usuarioParameter);
        }
    
        public virtual ObjectResult<DatosProyectoCotizacion> DatosProyectoCotizacion(Nullable<int> id_proyecto)
        {
            var id_proyectoParameter = id_proyecto.HasValue ?
                new ObjectParameter("id_proyecto", id_proyecto) :
                new ObjectParameter("id_proyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosProyectoCotizacion>("DatosProyectoCotizacion", id_proyectoParameter);
        }
    
        public virtual ObjectResult<DetalleUltimoAvance> DetalleUltimoAvance(Nullable<int> id_codigo_cotizacion)
        {
            var id_codigo_cotizacionParameter = id_codigo_cotizacion.HasValue ?
                new ObjectParameter("id_codigo_cotizacion", id_codigo_cotizacion) :
                new ObjectParameter("id_codigo_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleUltimoAvance>("DetalleUltimoAvance", id_codigo_cotizacionParameter);
        }
    
        public virtual ObjectResult<ListadoAvanceProyectosTotal> ListadoAvanceProyectosTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoAvanceProyectosTotal>("ListadoAvanceProyectosTotal");
        }
    
        public virtual int ActualizarEjecucionNotificacion(Nullable<long> id, string detalle, Nullable<bool> estado, Nullable<long> identificadorTarea)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var identificadorTareaParameter = identificadorTarea.HasValue ?
                new ObjectParameter("identificadorTarea", identificadorTarea) :
                new ObjectParameter("identificadorTarea", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEjecucionNotificacion", idParameter, detalleParameter, estadoParameter, identificadorTareaParameter);
        }
    
        public virtual int ActualizarEstadoEnvioNotificacion(Nullable<long> id, Nullable<bool> estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarEstadoEnvioNotificacion", idParameter, estadoParameter);
        }
    
        public virtual ObjectResult<ListadoTipoNotificaciones> ListadoTipoNotificaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoTipoNotificaciones>("ListadoTipoNotificaciones");
        }
    
        public virtual ObjectResult<ListadoTablaPlanes> ListadoTablaPlanes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoTablaPlanes>("ListadoTablaPlanes");
        }
    
        public virtual ObjectResult<ListadoComercios> ListadoComercios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoComercios>("ListadoComercios");
        }
    
        public virtual ObjectResult<ListadoClienteLineaNegocio> ListadoClienteLineaNegocio(string linea_negocio)
        {
            var linea_negocioParameter = linea_negocio != null ?
                new ObjectParameter("linea_negocio", linea_negocio) :
                new ObjectParameter("linea_negocio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoClienteLineaNegocio>("ListadoClienteLineaNegocio", linea_negocioParameter);
        }
    
        public virtual ObjectResult<ListadoCargaPTOP> ListadoCargaPTOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCargaPTOP>("ListadoCargaPTOP");
        }
    
        public virtual ObjectResult<NotificacionesCompletasInfo> ListadoNotificacionesCompletas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificacionesCompletasInfo>("ListadoNotificacionesCompletas");
        }
    
        public virtual ObjectResult<CalculoValoresFacturaPTOP> CalculoValoresFacturaPTOP(string nombrePlan, Nullable<int> nume_transacciones, Nullable<decimal> valor_transacciones, Nullable<bool> es_certificacion, Nullable<decimal> porcentaje_iva, Nullable<decimal> valor_certificacion, Nullable<decimal> descuento)
        {
            var nombrePlanParameter = nombrePlan != null ?
                new ObjectParameter("nombrePlan", nombrePlan) :
                new ObjectParameter("nombrePlan", typeof(string));
    
            var nume_transaccionesParameter = nume_transacciones.HasValue ?
                new ObjectParameter("nume_transacciones", nume_transacciones) :
                new ObjectParameter("nume_transacciones", typeof(int));
    
            var valor_transaccionesParameter = valor_transacciones.HasValue ?
                new ObjectParameter("valor_transacciones", valor_transacciones) :
                new ObjectParameter("valor_transacciones", typeof(decimal));
    
            var es_certificacionParameter = es_certificacion.HasValue ?
                new ObjectParameter("es_certificacion", es_certificacion) :
                new ObjectParameter("es_certificacion", typeof(bool));
    
            var porcentaje_ivaParameter = porcentaje_iva.HasValue ?
                new ObjectParameter("porcentaje_iva", porcentaje_iva) :
                new ObjectParameter("porcentaje_iva", typeof(decimal));
    
            var valor_certificacionParameter = valor_certificacion.HasValue ?
                new ObjectParameter("valor_certificacion", valor_certificacion) :
                new ObjectParameter("valor_certificacion", typeof(decimal));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("descuento", descuento) :
                new ObjectParameter("descuento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalculoValoresFacturaPTOP>("CalculoValoresFacturaPTOP", nombrePlanParameter, nume_transaccionesParameter, valor_transaccionesParameter, es_certificacionParameter, porcentaje_ivaParameter, valor_certificacionParameter, descuentoParameter);
        }
    
        public virtual int GeneraFactruasPTOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GeneraFactruasPTOP");
        }
    
        public virtual ObjectResult<GeneraFactruasPTOPSAFI> GeneraFactruasPTOPSAFI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneraFactruasPTOPSAFI>("GeneraFactruasPTOPSAFI");
        }
    
        public virtual int Actualizar_FacturaPTOP(Nullable<int> id_factura, string nume_fact, string nota_cred)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            var nume_factParameter = nume_fact != null ?
                new ObjectParameter("nume_fact", nume_fact) :
                new ObjectParameter("nume_fact", typeof(string));
    
            var nota_credParameter = nota_cred != null ?
                new ObjectParameter("nota_cred", nota_cred) :
                new ObjectParameter("nota_cred", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_FacturaPTOP", id_facturaParameter, nume_factParameter, nota_credParameter);
        }
    
        public virtual ObjectResult<ListadoFacturasPTOPSAFI> ListadoFacturasPTOPSAFI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoFacturasPTOPSAFI>("ListadoFacturasPTOPSAFI");
        }
    
        public virtual ObjectResult<FacturaPTOPSAFI> FacturaPTOPSAFI(Nullable<int> id_factura)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacturaPTOPSAFI>("FacturaPTOPSAFI", id_facturaParameter);
        }
    
        public virtual int Anular_FacturaPTOP(Nullable<int> id_factura, Nullable<int> accion)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Anular_FacturaPTOP", id_facturaParameter, accionParameter);
        }
    
        public virtual int Activar_FacturaPTOP(Nullable<int> id_factura)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Activar_FacturaPTOP", id_facturaParameter);
        }
    
        public virtual int Actualizar_FacturaPTOP_NC(Nullable<int> id_factura, string nume_nc)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            var nume_ncParameter = nume_nc != null ?
                new ObjectParameter("nume_nc", nume_nc) :
                new ObjectParameter("nume_nc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_FacturaPTOP_NC", id_facturaParameter, nume_ncParameter);
        }
    
        public virtual ObjectResult<ConsultarCargaPTOP> ConsultarCargaPTOP(Nullable<int> id_carga_PTOP)
        {
            var id_carga_PTOPParameter = id_carga_PTOP.HasValue ?
                new ObjectParameter("id_carga_PTOP", id_carga_PTOP) :
                new ObjectParameter("id_carga_PTOP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCargaPTOP>("ConsultarCargaPTOP", id_carga_PTOPParameter);
        }
    
        public virtual ObjectResult<GeneraCodigoNotaCredito> GeneraCodigoNotaCredito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneraCodigoNotaCredito>("GeneraCodigoNotaCredito");
        }
    
        public virtual ObjectResult<ListadoCargaPTOPExcel> ListadoCargaPTOPExcel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCargaPTOPExcel>("ListadoCargaPTOPExcel");
        }
    
        public virtual ObjectResult<ListadoParametrosSistemas> ListadoParametrosSistemas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoParametrosSistemas>("ListadoParametrosSistemas");
        }
    
        public virtual ObjectResult<ListadoAsignacionSolicitudes> ListadoAsignacionSolicitudes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoAsignacionSolicitudes>("ListadoAsignacionSolicitudes");
        }
    
        public virtual ObjectResult<DatosSolicitudCliente> DatosSolicitudCliente(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosSolicitudCliente>("DatosSolicitudCliente", id_solicitudParameter);
        }
    
        public virtual ObjectResult<AdjuntosSolicitud> AdjuntosSolicitud(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdjuntosSolicitud>("AdjuntosSolicitud", id_solicitudParameter);
        }
    
        public virtual ObjectResult<UrlExternosSolicitud> UrlExternosSolicitud(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrlExternosSolicitud>("UrlExternosSolicitud", id_solicitudParameter);
        }
    
        public virtual ObjectResult<CamposPersonalizadosSolicitud> CamposPersonalizadosSolicitud(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CamposPersonalizadosSolicitud>("CamposPersonalizadosSolicitud", id_solicitudParameter);
        }
    
        public virtual ObjectResult<ActaInfo> ConsultarActa(Nullable<long> iDActa, string codigoActa)
        {
            var iDActaParameter = iDActa.HasValue ?
                new ObjectParameter("IDActa", iDActa) :
                new ObjectParameter("IDActa", typeof(long));
    
            var codigoActaParameter = codigoActa != null ?
                new ObjectParameter("CodigoActa", codigoActa) :
                new ObjectParameter("CodigoActa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActaInfo>("ConsultarActa", iDActaParameter, codigoActaParameter);
        }
    
        public virtual ObjectResult<ActasInformacionGeneralInfo> ListadoActas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActasInformacionGeneralInfo>("ListadoActas");
        }
    
        public virtual ObjectResult<CodigoActaInfo> GenerarCodigoActa(Nullable<int> iDTipoActa)
        {
            var iDTipoActaParameter = iDTipoActa.HasValue ?
                new ObjectParameter("IDTipoActa", iDTipoActa) :
                new ObjectParameter("IDTipoActa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodigoActaInfo>("GenerarCodigoActa", iDTipoActaParameter);
        }
    
        public virtual ObjectResult<SolicitudClienteExternoInfo> ListadoSolicitudClienteExterno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SolicitudClienteExternoInfo>("ListadoSolicitudClienteExterno");
        }
    
        public virtual ObjectResult<SolicitudClienteInternoInfo> ListadoSolicitudClienteInterno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SolicitudClienteInternoInfo>("ListadoSolicitudClienteInterno");
        }
    
        public virtual ObjectResult<SolicitudClienteExternoInfo> ConsultarSolicitudClienteExterno(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SolicitudClienteExternoInfo>("ConsultarSolicitudClienteExterno", idParameter);
        }
    
        public virtual ObjectResult<SolicitudClienteInternoInfo> ConsultarSolicitudClienteInterno(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SolicitudClienteInternoInfo>("ConsultarSolicitudClienteInterno", idParameter);
        }
    
        public virtual ObjectResult<OrganigramaInfo> ListadoOrganigrama(Nullable<int> iDOrganigrama)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrganigramaInfo>("ListadoOrganigrama", iDOrganigramaParameter);
        }
    
        public virtual ObjectResult<OrganigramaInfo> ConsultarOrganigrama(Nullable<int> iDOrganigrama)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrganigramaInfo>("ConsultarOrganigrama", iDOrganigramaParameter);
        }
    
        public virtual ObjectResult<CostosSublineaNegocioInfo> ConsultarCostosSublineaNegocio(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CostosSublineaNegocioInfo>("ConsultarCostosSublineaNegocio", idParameter);
        }
    
        public virtual ObjectResult<CostosSublineaNegocioInfo> ListadoCostosSublineaNegocio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CostosSublineaNegocioInfo>("ListadoCostosSublineaNegocio");
        }
    
        public virtual ObjectResult<TrackingAsignacionProyectoInfo> ListadoDetalleTrackingAsignacionProyecto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrackingAsignacionProyectoInfo>("ListadoDetalleTrackingAsignacionProyecto");
        }
    
        public virtual ObjectResult<HistorialDetalleAsignacionProyectosInfo> ListadoHistorialDetalleAsignacionProyectos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HistorialDetalleAsignacionProyectosInfo>("ListadoHistorialDetalleAsignacionProyectos");
        }
    
        public virtual ObjectResult<ActaInfo> ListadoActasDetalles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActaInfo>("ListadoActasDetalles");
        }
    
        public virtual ObjectResult<ConsultarCodigoCotizacion> ConsultarCodigoCotizacion(Nullable<int> id_codigo_cotizacion)
        {
            var id_codigo_cotizacionParameter = id_codigo_cotizacion.HasValue ?
                new ObjectParameter("id_codigo_cotizacion", id_codigo_cotizacion) :
                new ObjectParameter("id_codigo_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCodigoCotizacion>("ConsultarCodigoCotizacion", id_codigo_cotizacionParameter);
        }
    
        public virtual ObjectResult<EstructuraOrganigramaInfo> ConsultarHijosOrganigramaPorUsuarioID(Nullable<int> iDOrganigrama, Nullable<int> iDEmpresa, Nullable<int> iD, Nullable<bool> dependientesCompletos)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            var iDEmpresaParameter = iDEmpresa.HasValue ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var dependientesCompletosParameter = dependientesCompletos.HasValue ?
                new ObjectParameter("DependientesCompletos", dependientesCompletos) :
                new ObjectParameter("DependientesCompletos", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstructuraOrganigramaInfo>("ConsultarHijosOrganigramaPorUsuarioID", iDOrganigramaParameter, iDEmpresaParameter, iDParameter, dependientesCompletosParameter);
        }
    
        public virtual ObjectResult<NivelOrganigramaInfo> ConsultarNivelOrganigrama(Nullable<int> iDOrganigrama, Nullable<int> iDEmpresa)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            var iDEmpresaParameter = iDEmpresa.HasValue ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NivelOrganigramaInfo>("ConsultarNivelOrganigrama", iDOrganigramaParameter, iDEmpresaParameter);
        }
    
        public virtual ObjectResult<EstructuraOrganigramaInfo> ConsultarEstructuraOrganigrama(Nullable<int> iDOrganigrama, Nullable<int> iDEmpresa, Nullable<int> iD)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            var iDEmpresaParameter = iDEmpresa.HasValue ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstructuraOrganigramaInfo>("ConsultarEstructuraOrganigrama", iDOrganigramaParameter, iDEmpresaParameter, iDParameter);
        }
    
        public virtual ObjectResult<EstructuraOrganigramaInfo> ConsultarEstructuraOrganigramaByRangoNivel(Nullable<int> iDOrganigrama, Nullable<int> iDEmpresa, Nullable<int> nivelInicial, Nullable<int> nivelFinal)
        {
            var iDOrganigramaParameter = iDOrganigrama.HasValue ?
                new ObjectParameter("IDOrganigrama", iDOrganigrama) :
                new ObjectParameter("IDOrganigrama", typeof(int));
    
            var iDEmpresaParameter = iDEmpresa.HasValue ?
                new ObjectParameter("IDEmpresa", iDEmpresa) :
                new ObjectParameter("IDEmpresa", typeof(int));
    
            var nivelInicialParameter = nivelInicial.HasValue ?
                new ObjectParameter("NivelInicial", nivelInicial) :
                new ObjectParameter("NivelInicial", typeof(int));
    
            var nivelFinalParameter = nivelFinal.HasValue ?
                new ObjectParameter("NivelFinal", nivelFinal) :
                new ObjectParameter("NivelFinal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstructuraOrganigramaInfo>("ConsultarEstructuraOrganigramaByRangoNivel", iDOrganigramaParameter, iDEmpresaParameter, nivelInicialParameter, nivelFinalParameter);
        }
    
        public virtual ObjectResult<ListadoBodega> ListadoBodega()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoBodega>("ListadoBodega");
        }
    
        public virtual ObjectResult<ListadoProducto> ListadoProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoProducto>("ListadoProducto");
        }
    
        public virtual ObjectResult<ListadoCodigosPrefacturar> ListadoCodigosPrefacturar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoCodigosPrefacturar>("ListadoCodigosPrefacturar");
        }
    
        public virtual ObjectResult<ListadoPresupuestoPrefacturaSAFI> ListadoPresupuestoPrefacturaSAFI(Nullable<int> id_codigo_cotizacion)
        {
            var id_codigo_cotizacionParameter = id_codigo_cotizacion.HasValue ?
                new ObjectParameter("id_codigo_cotizacion", id_codigo_cotizacion) :
                new ObjectParameter("id_codigo_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPresupuestoPrefacturaSAFI>("ListadoPresupuestoPrefacturaSAFI", id_codigo_cotizacionParameter);
        }
    
        public virtual ObjectResult<usp_g_codigo_documento> usp_g_codigo_documento(string tipo_documento)
        {
            var tipo_documentoParameter = tipo_documento != null ?
                new ObjectParameter("tipo_documento", tipo_documento) :
                new ObjectParameter("tipo_documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_g_codigo_documento>("usp_g_codigo_documento", tipo_documentoParameter);
        }
    
        public virtual ObjectResult<MatrizPresupuestoInfo> ConsultarMatrizPresupuesto(Nullable<int> iD, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MatrizPresupuestoInfo>("ConsultarMatrizPresupuesto", iDParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoPrefacturasSAFI(Nullable<int> iDCliente, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> ejecutivoID)
        {
            var iDClienteParameter = iDCliente.HasValue ?
                new ObjectParameter("IDCliente", iDCliente) :
                new ObjectParameter("IDCliente", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var ejecutivoIDParameter = ejecutivoID.HasValue ?
                new ObjectParameter("ejecutivoID", ejecutivoID) :
                new ObjectParameter("ejecutivoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoPrefacturasSAFI", iDClienteParameter, fechaInicioParameter, fechaFinParameter, ejecutivoIDParameter);
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ConsultarPrefacturaSAFI(Nullable<long> iD, string numeroDocumento, string codigoCotizacion)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var numeroDocumentoParameter = numeroDocumento != null ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(string));
    
            var codigoCotizacionParameter = codigoCotizacion != null ?
                new ObjectParameter("codigoCotizacion", codigoCotizacion) :
                new ObjectParameter("codigoCotizacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ConsultarPrefacturaSAFI", iDParameter, numeroDocumentoParameter, codigoCotizacionParameter);
        }
    
        public virtual ObjectResult<ListadoPresupuestosFacturar> ListadoPresupuestosFacturar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPresupuestosFacturar>("ListadoPresupuestosFacturar");
        }
    
        public virtual ObjectResult<ListadoFacturarSAFI> ListadoFacturarSAFI(Nullable<int> id_facturacion_safi)
        {
            var id_facturacion_safiParameter = id_facturacion_safi.HasValue ?
                new ObjectParameter("id_facturacion_safi", id_facturacion_safi) :
                new ObjectParameter("id_facturacion_safi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoFacturarSAFI>("ListadoFacturarSAFI", id_facturacion_safiParameter);
        }
    
        public virtual ObjectResult<ConsultarDatosClienteSAFI> ConsultarDatosClienteSAFI(string clave)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarDatosClienteSAFI>("ConsultarDatosClienteSAFI", claveParameter);
        }
    
        public virtual int AsignacionSolicitudesAutomatico(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsignacionSolicitudesAutomatico", id_solicitudParameter);
        }
    
        public virtual ObjectResult<ResultadoConsolidacionPrefacturas> ResultadoConsolidacionPrefacturas(string idsPrefacturas)
        {
            var idsPrefacturasParameter = idsPrefacturas != null ?
                new ObjectParameter("IdsPrefacturas", idsPrefacturas) :
                new ObjectParameter("IdsPrefacturas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResultadoConsolidacionPrefacturas>("ResultadoConsolidacionPrefacturas", idsPrefacturasParameter);
        }
    
        public virtual int ConsolidarPrefactura(string ids, Nullable<int> usuarioID, Nullable<int> idPrefacturaDefinitiva)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(string));
    
            var usuarioIDParameter = usuarioID.HasValue ?
                new ObjectParameter("usuarioID", usuarioID) :
                new ObjectParameter("usuarioID", typeof(int));
    
            var idPrefacturaDefinitivaParameter = idPrefacturaDefinitiva.HasValue ?
                new ObjectParameter("idPrefacturaDefinitiva", idPrefacturaDefinitiva) :
                new ObjectParameter("idPrefacturaDefinitiva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConsolidarPrefactura", idsParameter, usuarioIDParameter, idPrefacturaDefinitivaParameter);
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoCompletoDocumentosSAFI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoCompletoDocumentosSAFI");
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoPrefacturasAprobadas(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoPrefacturasAprobadas", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ActualizarFacturaSAFI> ActualizarFacturaSAFI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActualizarFacturaSAFI>("ActualizarFacturaSAFI");
        }
    
        public virtual int usp_guarda_envio_correo_notificaciones(Nullable<int> tipo, Nullable<int> idCotizador, string cuerpo, Nullable<int> usuario, string clave)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var idCotizadorParameter = idCotizador.HasValue ?
                new ObjectParameter("idCotizador", idCotizador) :
                new ObjectParameter("idCotizador", typeof(int));
    
            var cuerpoParameter = cuerpo != null ?
                new ObjectParameter("cuerpo", cuerpo) :
                new ObjectParameter("cuerpo", typeof(string));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_guarda_envio_correo_notificaciones", tipoParameter, idCotizadorParameter, cuerpoParameter, usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<ListadoANSCliente> ListadoANSCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoANSCliente>("ListadoANSCliente");
        }
    
        public virtual ObjectResult<ComentariosSolicitudInfo> ListadoComentariosSolicitud(Nullable<long> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComentariosSolicitudInfo>("ListadoComentariosSolicitud", idSolicitudParameter);
        }
    
        public virtual ObjectResult<ResumenSolicitudesSolicitanteInfo> ListadoResumenSolicitudesSolicitante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResumenSolicitudesSolicitanteInfo>("ListadoResumenSolicitudesSolicitante");
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoResumenPrefacturas(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoResumenPrefacturas", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<ListadoANSDelCliente> ListadoANSDelCliente(Nullable<int> id_solicita, Nullable<int> id_tipo_solicitud)
        {
            var id_solicitaParameter = id_solicita.HasValue ?
                new ObjectParameter("id_solicita", id_solicita) :
                new ObjectParameter("id_solicita", typeof(int));
    
            var id_tipo_solicitudParameter = id_tipo_solicitud.HasValue ?
                new ObjectParameter("id_tipo_solicitud", id_tipo_solicitud) :
                new ObjectParameter("id_tipo_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoANSDelCliente>("ListadoANSDelCliente", id_solicitaParameter, id_tipo_solicitudParameter);
        }
    
        public virtual ObjectResult<MenuRutaAcceso> ConsultarMenuRutaAcceso(Nullable<int> id_rol)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuRutaAcceso>("ConsultarMenuRutaAcceso", id_rolParameter);
        }
    
        public virtual int GuardarRolMenuPermisos(Nullable<int> idRol, Nullable<int> idPerfil, Nullable<int> idMenu, Nullable<int> idAccion, Nullable<int> createdBy, Nullable<int> updateBy, Nullable<System.DateTime> createAt, Nullable<System.DateTime> updateAt, Nullable<bool> estado)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            var idAccionParameter = idAccion.HasValue ?
                new ObjectParameter("idAccion", idAccion) :
                new ObjectParameter("idAccion", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(int));
    
            var updateByParameter = updateBy.HasValue ?
                new ObjectParameter("updateBy", updateBy) :
                new ObjectParameter("updateBy", typeof(int));
    
            var createAtParameter = createAt.HasValue ?
                new ObjectParameter("createAt", createAt) :
                new ObjectParameter("createAt", typeof(System.DateTime));
    
            var updateAtParameter = updateAt.HasValue ?
                new ObjectParameter("updateAt", updateAt) :
                new ObjectParameter("updateAt", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarRolMenuPermisos", idRolParameter, idPerfilParameter, idMenuParameter, idAccionParameter, createdByParameter, updateByParameter, createAtParameter, updateAtParameter, estadoParameter);
        }
    
        public virtual int LimpiarRolMenuPermisosCompleto(Nullable<int> idRol, Nullable<int> idPerfil)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LimpiarRolMenuPermisosCompleto", idRolParameter, idPerfilParameter);
        }
    
        public virtual ObjectResult<UsuarioRolMenuPermiso> ListadoRolPerfilMenuPermisos(Nullable<int> id_rol, Nullable<int> id_perfil)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioRolMenuPermiso>("ListadoRolPerfilMenuPermisos", id_rolParameter, id_perfilParameter);
        }
    
        public virtual ObjectResult<UsuarioRolMenuPermiso> ConsultarUsuarioRolMenuPermiso(Nullable<int> id_usuario, string controlador)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var controladorParameter = controlador != null ?
                new ObjectParameter("controlador", controlador) :
                new ObjectParameter("controlador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioRolMenuPermiso>("ConsultarUsuarioRolMenuPermiso", id_usuarioParameter, controladorParameter);
        }
    
        public virtual int LimpiarRolMenuPermisos(Nullable<int> idRol, Nullable<int> idPerfil, Nullable<int> idMenu)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LimpiarRolMenuPermisos", idRolParameter, idPerfilParameter, idMenuParameter);
        }
    
        public virtual ObjectResult<MarcaPortales> ConsultarPortales(Nullable<int> id_solicitud)
        {
            var id_solicitudParameter = id_solicitud.HasValue ?
                new ObjectParameter("id_solicitud", id_solicitud) :
                new ObjectParameter("id_solicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarcaPortales>("ConsultarPortales", id_solicitudParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ConsultarCantidadComentariosSolictud(Nullable<long> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("idSolicitud", idSolicitud) :
                new ObjectParameter("idSolicitud", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarCantidadComentariosSolictud", idSolicitudParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ConsultarCantidadRespuestaComentario(Nullable<long> idComentario)
        {
            var idComentarioParameter = idComentario.HasValue ?
                new ObjectParameter("idComentario", idComentario) :
                new ObjectParameter("idComentario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConsultarCantidadRespuestaComentario", idComentarioParameter);
        }
    
        public virtual ObjectResult<ComentariosSolicitudInfo> ConsultarComentariosSolicitud(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComentariosSolicitudInfo>("ConsultarComentariosSolicitud", idParameter);
        }
    
        public virtual ObjectResult<ListadoPresupuestosAprobacionEjecutivo> ListadoPresupuestosAprobacionEjecutivo(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPresupuestosAprobacionEjecutivo>("ListadoPresupuestosAprobacionEjecutivo", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ConsultarPresupuestoFacturados> ConsultarPresupuestoFacturados(Nullable<int> iD, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarPresupuestoFacturados>("ConsultarPresupuestoFacturados", iDParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<ListadoProductosGestor> ListadoProductosGestor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoProductosGestor>("ListadoProductosGestor");
        }
    
        public virtual ObjectResult<ResultadoConsolidacionPrefacturasDetallado> ResultadoConsolidacionPrefacturasDetallado(string idsPrefacturas)
        {
            var idsPrefacturasParameter = idsPrefacturas != null ?
                new ObjectParameter("IdsPrefacturas", idsPrefacturas) :
                new ObjectParameter("IdsPrefacturas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResultadoConsolidacionPrefacturasDetallado>("ResultadoConsolidacionPrefacturasDetallado", idsPrefacturasParameter);
        }
    
        public virtual ObjectResult<ConsultarPrefacturaSAFIDetalle> ConsultarPrefacturaSAFIDetalle(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarPrefacturaSAFIDetalle>("ConsultarPrefacturaSAFIDetalle", iDParameter);
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoPrefacturasAprobadasReversar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoPrefacturasAprobadasReversar");
        }
    
        public virtual int ReversarConsolidacionPrefactura(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReversarConsolidacionPrefactura", idParameter);
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoFacturasAprobadas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoFacturasAprobadas");
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoFacturasAprobadasParaAnular()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoFacturasAprobadasParaAnular");
        }
    
        public virtual ObjectResult<PrefacturaSAFIInfo> ListadoFacturasAprobadasParaGenerarNotaCredito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrefacturaSAFIInfo>("ListadoFacturasAprobadasParaGenerarNotaCredito");
        }
    
        public virtual ObjectResult<ListadoPrefacturasRechazadas> ListadoPrefacturasRechazadas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPrefacturasRechazadas>("ListadoPrefacturasRechazadas");
        }
    
        public virtual int ActualizarPresupuestosSAFI(Nullable<int> tipoAccion, string numeroPrefactura, string numeroPrefacturaConsolidada)
        {
            var tipoAccionParameter = tipoAccion.HasValue ?
                new ObjectParameter("tipoAccion", tipoAccion) :
                new ObjectParameter("tipoAccion", typeof(int));
    
            var numeroPrefacturaParameter = numeroPrefactura != null ?
                new ObjectParameter("numeroPrefactura", numeroPrefactura) :
                new ObjectParameter("numeroPrefactura", typeof(string));
    
            var numeroPrefacturaConsolidadaParameter = numeroPrefacturaConsolidada != null ?
                new ObjectParameter("numeroPrefacturaConsolidada", numeroPrefacturaConsolidada) :
                new ObjectParameter("numeroPrefacturaConsolidada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarPresupuestosSAFI", tipoAccionParameter, numeroPrefacturaParameter, numeroPrefacturaConsolidadaParameter);
        }
    
        public virtual ObjectResult<ListadoPresupuestosAprobadosEjecutivo> ListadoPresupuestosAprobadosEjecutivo(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPresupuestosAprobadosEjecutivo>("ListadoPresupuestosAprobadosEjecutivo", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ListadoPresupuestosAprobadosEjecutivoFinal> ListadoPresupuestosAprobadosEjecutivoFinal(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoPresupuestosAprobadosEjecutivoFinal>("ListadoPresupuestosAprobadosEjecutivoFinal", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ListadoResumenPrefacturasAprobadas> ListadoResumenPrefacturasAprobadas(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoResumenPrefacturasAprobadas>("ListadoResumenPrefacturasAprobadas", id_usuarioParameter);
        }
    
        public virtual ObjectResult<ListadoResumenPrefacturasAprobadas> ListadoResumenPrefacturasAprobadasHistorico(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoResumenPrefacturasAprobadas>("ListadoResumenPrefacturasAprobadasHistorico", id_usuarioParameter);
        }
    }
}
