//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoTablaPlanes
    {
        public int Codigo { get; set; }
        public string Nombre_Plan { get; set; }
        public Nullable<decimal> Transaccion_Minima { get; set; }
        public Nullable<decimal> Transaccion_Maxima { get; set; }
        public Nullable<decimal> Valor_Minimo { get; set; }
        public Nullable<decimal> Valor_Maximo { get; set; }
        public Nullable<decimal> Costo_Transaccion { get; set; }
        public string Tipo_Cobro { get; set; }
        public string Estado_Plan { get; set; }
        public Nullable<decimal> Valor_Pago_Mínimo { get; set; }
    }
}
