//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoUsuarios
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Nombres_Completos { get; set; }
        public string Cliente_Asociado { get; set; }
        public string Area_o_Departamento { get; set; }
        public string Cargo { get; set; }
        public string País { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Rol { get; set; }
        public int Codigo_Vendedor { get; set; }
        public string Estado { get; set; }
        public string NombreEmpresa { get; set; }
        public Nullable<bool> usar_organigrama { get; set; }
        public int id_cliente { get; set; }
    }
}
