//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoCliente
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string RUC { get; set; }
        public string Razon_Social { get; set; }
        public string Nombre_Comercial { get; set; }
        public string Tamanio_Empresa { get; set; }
        public string sector { get; set; }
        public string Pais { get; set; }
        public string ciudad { get; set; }
        public string Direccion { get; set; }
        public string Tipo_Cliente { get; set; }
        public string Tipo_Zoho { get; set; }
        public string Estado { get; set; }
        public string PotencialCrecimiento { get; set; }
        public string CategorizacionCliente { get; set; }
        public string EtapaCliente { get; set; }
    }
}
