//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoParametrosSistemas
    {
        public int id_parametro { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string valor { get; set; }
        public string tipo { get; set; }
        public string estado { get; set; }
    }
}
