//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoOrdenMenu
    {
        public int Id { get; set; }
        public string Opcion_Menu { get; set; }
        public Nullable<int> orden_menu { get; set; }
        public Nullable<int> id_menu_padre { get; set; }
    }
}
