//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoAvanceProyectosTotal
    {
        public Nullable<int> id { get; set; }
        public string CodigoCotizacion { get; set; }
        public string NombreProyecto { get; set; }
        public string Cliente { get; set; }
        public string Ejecutivo { get; set; }
        public string Fase { get; set; }
        public int HorasProg { get; set; }
        public string FechaInicioProg { get; set; }
        public string FechaFinProg { get; set; }
        public int HorasReal { get; set; }
        public string FechaInicioReal { get; set; }
        public string FechaFinReal { get; set; }
        public string AvanceProgramado { get; set; }
        public string AvanceReal { get; set; }
        public string Avance { get; set; }
        public string RealProgramado { get; set; }
        public Nullable<int> Dias { get; set; }
        public string FechaAvance { get; set; }
        public Nullable<decimal> RegistradoReal { get; set; }
        public string Descripcion { get; set; }
        public string Ejecutado { get; set; }
        public string En_Ejecucion { get; set; }
        public string Bloqueantes { get; set; }
        public string ProximosPasos { get; set; }
        public string Responsable { get; set; }
    }
}
