//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoComercios
    {
        public int Codigo { get; set; }
        public string ID_Comercio { get; set; }
        public string Comercio { get; set; }
        public string RazonSocial { get; set; }
        public string fecha_salida_produccion { get; set; }
        public string fecha_inactivo { get; set; }
        public Nullable<int> meses_activos { get; set; }
        public Nullable<int> meses_inactivos { get; set; }
        public string EstatusContrato { get; set; }
        public string TipoSubsidio { get; set; }
        public string Agrupacion { get; set; }
        public string CompartidoPTOP { get; set; }
        public string Estado_comercio { get; set; }
        public string CanalComunicacion { get; set; }
        public string Tipificacion { get; set; }
        public string FechaComunicacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PorcentajeIva { get; set; }
        public string cobro_porcentaje { get; set; }
    }
}
