//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoANSCliente
    {
        public int Codigo { get; set; }
        public string Cliente { get; set; }
        public string RUC { get; set; }
        public string TipoRequerimiento { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public string EstadoANS { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> id_tipo_solicitud { get; set; }
        public string TipoSolicitud { get; set; }
    }
}
