//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoCargaPTOP
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoComercio { get; set; }
        public string IDComercio { get; set; }
        public string NombreComercio { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public string RucCliente { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> CodigoPlan { get; set; }
        public string NombrePlan { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PorcentajeIva { get; set; }
        public Nullable<decimal> ValorCertificacion { get; set; }
        public Nullable<int> TransaccionesAprobadas { get; set; }
        public Nullable<int> TransaccionesRechazadas { get; set; }
        public Nullable<decimal> MontoVendido { get; set; }
        public Nullable<decimal> MontoRechazado { get; set; }
        public string Observaciones { get; set; }
        public string Correos { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string Estado { get; set; }
        public string fecha_salida_produccion { get; set; }
        public string fecha_inactivo { get; set; }
        public string FacturableCertificacion { get; set; }
        public string FacturableMensual { get; set; }
        public string estado_comercio { get; set; }
        public string EstatusContrato { get; set; }
        public string Agrupacion { get; set; }
    }
}
