//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoContacto
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Cliente { get; set; }
        public string TipoContacto { get; set; }
        public string NombresCompletos { get; set; }
        public string Cargo { get; set; }
        public string Mail { get; set; }
        public string Prefijo { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public string Celular { get; set; }
        public string Estado { get; set; }
    }
}
