//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoCabeceraCotizadorPDF
    {
        public string Código_Cotización { get; set; }
        public string Versión { get; set; }
        public string Fecha_Cotización { get; set; }
        public string Fecha_Vencimiento { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public string Nombre_Proyecto { get; set; }
        public decimal Subtotal { get; set; }
        public string Responsable { get; set; }
        public string Estado { get; set; }
        public string EstadoCotizacion { get; set; }
    }
}
