//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoProducto
    {
        public int Id { get; set; }
        public string Bodega { get; set; }
        public string CodigoBodega { get; set; }
        public string Tarifario { get; set; }
        public string NombreProducto { get; set; }
        public string CodigooProducto { get; set; }
        public string Estado { get; set; }
    }
}
