//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoMenu
    {
        public string Padre { get; set; }
        public string Opcion_Menu { get; set; }
        public string Ruta_Acceso { get; set; }
        public string Estado { get; set; }
        public int Id { get; set; }
    }
}
