//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoProductosGestor
    {
        public int Id { get; set; }
        public string LineaNegocio { get; set; }
        public string SublineaNegocio { get; set; }
        public string ProductoComercial { get; set; }
        public string ProductoGeneral { get; set; }
        public string Estado { get; set; }
    }
}
