//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoCodigosPrefacturar
    {
        public string CodigoCotizacion { get; set; }
        public string Detalle { get; set; }
        public string RUC { get; set; }
        public string Cliente { get; set; }
        public string Correo { get; set; }
        public string Ejecutivo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public int Id { get; set; }
    }
}
