//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ListadoTipoNotificaciones
    {
        public int id_notificacion { get; set; }
        public string Nombre_Notificacion { get; set; }
        public string Descripcion_Tarifario { get; set; }
        public Nullable<int> Tiempo_Espera { get; set; }
        public string Estado_Notificacion { get; set; }
    }
}
