//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCreditoPTOP
    {
        public int id_nota_credito_PTOP { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> secuencial { get; set; }
        public string numero_nota_credito { get; set; }
        public string motivo { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha_nota_credito { get; set; }
        public Nullable<bool> estado_nota_credito { get; set; }
    }
}
