//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ResultadoConsolidacionPrefacturasDetallado
    {
        public string codigo_producto { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> IvaGeneral { get; set; }
        public Nullable<decimal> DescuentoGeneral { get; set; }
        public Nullable<decimal> SubtotalGeneral { get; set; }
        public Nullable<decimal> TotalPagGeneral { get; set; }
        public string CodigoBodega { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public string CentroCosto { get; set; }
        public string id_forma_pago { get; set; }
    }
}
