//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class ResultadoConsolidacionPrefacturas
    {
        public int Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> TotalPago { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string nombre_comercial_cliente { get; set; }
        public string ruc_ci_cliente { get; set; }
        public string correos_facturacion { get; set; }
    }
}
