//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAFIGeneralDetalle
    {
        public int id_facturacion_safi_detalle { get; set; }
        public Nullable<int> id_facturacion_safi { get; set; }
        public Nullable<int> id_codigo_producto { get; set; }
        public Nullable<int> id_forma_pago { get; set; }
        public Nullable<int> id_centro_costos { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> subtotal_pago { get; set; }
        public Nullable<decimal> iva_pago { get; set; }
        public Nullable<decimal> descuento_pago { get; set; }
        public Nullable<decimal> total_pago { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
