//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Cliente_Usuario
    {
        public int id_solicitud_cliente_usuario { get; set; }
        public Nullable<int> id_usuario_interno { get; set; }
        public Nullable<int> id_solicitud { get; set; }
    }
}
