//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesDeRechazoPresupuestos
    {
        public long id_rechazo { get; set; }
        public Nullable<long> id_facturacion_safi { get; set; }
        public Nullable<System.DateTime> fecha_solicitud_rechazo { get; set; }
        public Nullable<long> id_tipo_rechazo { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
