//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Url_Externo
    {
        public int id_url_externo { get; set; }
        public Nullable<int> id_solicitud { get; set; }
        public string tipo { get; set; }
        public string detalle { get; set; }
        public string url { get; set; }
        public string NumeroTelefono { get; set; }
    }
}
