//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCliente
    {
        public int id_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_hora_solicitud { get; set; }
        public Nullable<int> id_solicitante { get; set; }
        public string area_1 { get; set; }
        public string area_2 { get; set; }
        public string implementacion { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<int> id_subtipo { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string op { get; set; }
        public string mkt { get; set; }
        public string nombre_proyecto { get; set; }
        public string descripcion_proyecto { get; set; }
        public Nullable<bool> estado { get; set; }
        public string empresa { get; set; }
        public Nullable<int> id_codigo_cotizacion { get; set; }
        public Nullable<int> id_estado_solicitud { get; set; }
        public Nullable<int> id_area_encargada { get; set; }
        public Nullable<bool> solicitud_urgente { get; set; }
        public Nullable<System.DateTime> fecha_hora_fin_solicitud { get; set; }
        public Nullable<int> id_ans_sla { get; set; }
    }
}
