//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class SublineaNegocioCodigoCotizacionInfo
    {
        public int IdSublineaNegocioCotizacion { get; set; }
        public int IdCodigoCotizacion { get; set; }
        public int CodigoCatalogoSublineaNegocio { get; set; }
        public string TextoCatalogoSublineaNegocio { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Estado { get; set; }
        public string codigo_cotizacion { get; set; }
    }
}
