//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SublineaNegocio
    {
        public int id_sublinea_negocio { get; set; }
        public int id_linea_negocio { get; set; }
        public string nombre { get; set; }
        public string descripcon { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
