//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaPlanes
    {
        public int id_plan { get; set; }
        public string nombre_plan { get; set; }
        public Nullable<decimal> transaccion_minima { get; set; }
        public Nullable<decimal> transaccion_maxima { get; set; }
        public Nullable<decimal> valor_minimo { get; set; }
        public Nullable<decimal> valor_maximo { get; set; }
        public Nullable<decimal> costo_x_transaccion { get; set; }
        public Nullable<decimal> valor_fijo { get; set; }
        public Nullable<bool> cobro_porcentaje { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
