//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifario
    {
        public int id_tarifario { get; set; }
        public string tipo_tarifario { get; set; }
        public Nullable<int> linea_negocio { get; set; }
        public Nullable<decimal> valor_tarifario { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<bool> gestion_tarifario { get; set; }
        public Nullable<bool> estado_tarifario { get; set; }
        public Nullable<int> id_empresa { get; set; }
    }
}
