//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class TarifarioInfo
    {
        public int id_tarifario { get; set; }
        public string Nombre_Tarifario { get; set; }
        public string Linea_de_Negocio { get; set; }
        public Nullable<decimal> Valor_Unitario { get; set; }
        public string Tipo_Tarifario { get; set; }
        public string Gestion_Tarifario { get; set; }
        public string Estado_Tarifario { get; set; }
        public string Empresa { get; set; }
    }
}
