//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class usp_b_lista_usuario
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string País { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Cargo { get; set; }
        public int Id { get; set; }
        public string Cliente { get; set; }
        public string Mail { get; set; }
        public string Celular { get; set; }
        public string Rol { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Area_Departamento { get; set; }
        public string Codigo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Codigo_Usuario { get; set; }
    }
}
