//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class usp_b_usuario
    {
        public int Código { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Asociado { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Departamento { get; set; }
        public string País { get; set; }
        public string Ciudad { get; set; }
        public string direccion_usuario { get; set; }
        public string mail_usuario { get; set; }
        public string telefono_usuario { get; set; }
        public string celular_usuario { get; set; }
        public Nullable<int> rol_id { get; set; }
        public string codigo_usuario { get; set; }
        public string clave_usuario { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> activo_usuario { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public int id_rol { get; set; }
        public string nombre_rol { get; set; }
        public string descripcion_rol { get; set; }
        public Nullable<bool> estado_rol { get; set; }
        public Nullable<int> secu_usua { get; set; }
        public Nullable<bool> reset_clave { get; set; }
        public Nullable<int> CodigoTipoUsuario { get; set; }
        public Nullable<bool> validacion_correo { get; set; }
    }
}
