//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo
{
    using System;
    
    public partial class usp_b_lista_catalogo
    {
        public int Código { get; set; }
        public string Nombre_Catálogo { get; set; }
        public string Descripción_Catálogo { get; set; }
        public string Estado { get; set; }
    }
}
