//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPPM.Entidades.Modelo.PlaceToPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComercioPlaceToPay
    {
        public int IDComercioPlaceToPay { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TipoCodigo { get; set; }
        public Nullable<int> Region { get; set; }
        public string NombresEjecutivo { get; set; }
        public string ApellidosEjecutivo { get; set; }
        public string CorreoElectronicoEjecutivo { get; set; }
        public Nullable<int> FormaContacto { get; set; }
        public string NombresContacto { get; set; }
        public string ApellidosContacto { get; set; }
        public string CorreoElectronicoLiderProyectoComercio { get; set; }
        public string NombresAdministrador { get; set; }
        public string ApellidosAdministrador { get; set; }
        public string NumeroCelularAdministrador { get; set; }
        public string IdentificacionAdministrador { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public string TipoCuentaBancaria { get; set; }
        public string BancoCuentaBancaria { get; set; }
        public string TelefonoParticular { get; set; }
        public Nullable<int> NumeroTransaccionesMensuales { get; set; }
        public string ProductoRecomendado { get; set; }
        public Nullable<decimal> MontoPromedioPorTransaccion { get; set; }
        public string Segmento { get; set; }
        public string Industria { get; set; }
        public string TipoDeServicio { get; set; }
        public string TiposCreditoDisponer { get; set; }
        public string Plazos { get; set; }
        public Nullable<int> TipoPropuesta { get; set; }
        public Nullable<int> FaseGestion { get; set; }
        public string PropuestaAdjuntada { get; set; }
        public string CodigoUnico { get; set; }
        public Nullable<System.DateTime> FechaAfiliacion { get; set; }
        public string RUC { get; set; }
        public string Establecimiento { get; set; }
        public string MID { get; set; }
        public string Especialidad { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public string RazonSocial { get; set; }
        public string DireccionComercio { get; set; }
        public string Prefijo1 { get; set; }
        public string Telefono1 { get; set; }
        public string Prefijo2 { get; set; }
        public string Telefono2 { get; set; }
        public string Prefijo3 { get; set; }
        public string Telefono3 { get; set; }
        public string Prefijo4 { get; set; }
        public string Telefono4 { get; set; }
        public string Mail { get; set; }
        public string Marca { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string IdentificacionRepresentanteLegal { get; set; }
    }
}
